Repository Jetty2020/random-interview, pull requests merged in 2022-04, with the labels that each got.

#7 Feat/3 random page
  .eslintrc.json
  package.json
  src/pages/random-interview/index.tsx
Labels: enhancement

#19 💄 레이아웃 width 수정
  src/components/landing/styled.ts
  src/components/layouts/HeaderPage.tsx
Labels: enhancement

#20 면접 질문 리스트 페이지 UI 개선
  src/components/common/ContainerPage.tsx
  src/components/questionList/Category.tsx
  src/components/questionList/ListCategory.tsx
  src/components/questionList/ListQuestion.tsx
  src/components/questionList/Question.tsx
  src/components/questionList/Title.tsx
  src/components/questionList/TitleList.tsx
  src/components/questionList/WrapperQuestion.tsx
  src/pages/list.tsx
Labels: enhancement

#15 Feat/9 random question
  src/components/ramdom-interview/QuestionList.tsx
  src/components/ramdom-interview/SettingForm.tsx
  src/components/ramdom-interview/StartInterview.tsx
  src/constants/categories.ts
  src/constants/questions.ts
  src/pages/random-interview/index.tsx
Labels: enhancement

#25 면접 질문 리스트 페이지 UI 개선
  src/components/questionList/Category.tsx
  src/components/questionList/ListCategory.tsx
  src/components/questionList/ListQuestion.tsx
  src/components/questionList/TitleList.tsx
  src/constants/questions.ts
Labels: bug, enhancement

#31 인터뷰 종료 후 푼 문제 화면에 렌더링
  src/components/ramdom-interview/QuestionList.tsx
  src/components/ramdom-interview/Quiz.tsx
  src/components/ramdom-interview/SettingForm.tsx
  src/components/ramdom-interview/StartInterview.tsx
  src/pages/random-interview/index.tsx
  yarn.lock
Labels: enhancement

#29 검색 기능 추가
  .prettierignore
  src/assets/icon/search.svg
  src/components/questionList/ListQuestion.tsx
  src/components/questionList/SearchBar.tsx
  src/components/questionList/TitlePage.tsx
  src/components/questionList/index.ts
  src/constants/questions.ts
  src/pages/list.tsx
  src/utils/debounce.ts
  tsconfig.json
Labels: enhancement

#33 Feat/26 media
  public/guideline.svg
  src/assets/icon/guideline.svg
  src/components/Media/index.tsx
  src/components/Media/styled.ts
  src/pages/random-play.tsx
  src/pages/result.tsx
Labels: enhancement

#35 인터뷰 종료 후 문제 보여주기
  src/components/questionList/Question.tsx
  src/components/ramdom-interview/QuestionList.tsx
  src/components/ramdom-interview/Quiz.tsx
  src/components/ramdom-interview/StartInterview.tsx
Labels: enhancement

#37 면접 질문 페이지 UI 개선
  src/components/layouts/HeaderPage.tsx
  src/components/questionList/Category.tsx
  src/components/questionList/Question.tsx
  src/components/questionList/TitleList.tsx
Labels: enhancement

#40 Feat/28 landing page refactoring
  src/components/landing/InterviewPage.tsx
  src/components/landing/ListPage.tsx
  src/components/landing/PageIntro.tsx
  src/components/landing/index.tsx
  src/components/landing/styled.ts
  src/components/layouts/HeaderPage.tsx
  src/pages/index.tsx
Labels: enhancement

#41 Feat/38 refactor components and utils
  src/components/questionList/Category.tsx
  src/components/questionList/ListCategory.tsx
  src/components/questionList/ListQuestion.tsx
  src/components/questionList/Pagination.tsx
  src/components/questionList/Question.tsx
  src/components/questionList/SearchBar.tsx
  src/components/questionList/TitleList.tsx
  src/components/questionList/TitlePage.tsx
  src/constants/questions.ts
  src/utils/pxToRem.ts
Labels: bug, enhancement

#43 Media 컴포넌트 적용
  src/assets/icon/guideline.svg
  src/components/Media/index.tsx
  src/components/Media/styled.ts
  src/components/questionList/Question.tsx
  src/components/ramdom-interview/QuestionList.tsx
  src/components/ramdom-interview/Quiz.tsx
  src/components/ramdom-interview/SettingForm.tsx
  src/components/ramdom-interview/StartInterview.tsx
  src/pages/random-interview/index.tsx
  src/pages/random-play.tsx
  src/pages/result.tsx
  src/pages/select.tsx
Labels: bug, enhancement

#48 🐛 장치에 따른 예외처리
  src/components/ramdom-interview/SettingForm.tsx
Labels: bug

#46 Feat/45 landing page routing
  src/components/landing/PageIntro.tsx
  src/components/landing/styled.ts
  src/components/layouts/HeaderPage.tsx
  src/pages/index.tsx
Labels: enhancement
